* Design
** Version 0
KeyDays shows the dates that are important to the user. The app displays dates and countdown days to the user.

- User can *scroll through* past dates and upcoming dates.
- Layout is optimized with the ViewHolder pattern.
- For each movie displayed, user can see the following details:
  + Tile, date, past days(or the days left)
- User interface imporved through styling nad coloring and using material design elements such as CardView and Navigation Drawer.
- The app is using Espresso to text the UI interactions.

** Version 1
Date: <2018-10-07 Sun>
MainActivity has left drawerLayout and on the right of the top has ADD button. The user can also change the layout to grid, verse visa.

Log in /Register Activity

*** Activities
1. MainActivity
Cover
List the recorded events -> Right wrap to delete
Menu
Add button -> AddDateActivity

2. LoginActivity

3. AddDateActivity

*** Database
1. table1: users. Record the user name, email and password.
2. table2: keydates. Each user has his own table, which is recorddate.

One-to-many relationship

**** The user table
primary\_key: user\_id

| id       | user\_name  | user\_email | user\_password |
|----------+------------+-------------+----------------|
|          |            |             |                |

#+BEGIN_SRC
CREATE TABLE user (
   id    INTEGER PRIMARY KEY AUTOINCREMENT,
   user_name  TEXT    NOT NULL,
   user_email TEXT    NOT NULL,
   user_password TEXT NOT NULL
);
#+END_SRC

**** The keydate table
primary\_key: keydate_id
foreign key: users(user\_id)

| keydate\_id | keydate\_name | user\_id | remaining\_days | past\_days |
|-------------+---------------+----------+-----------------+------------|
|             |               |          |                 |            |
#+BEGIN_SRC
CREATE TABLE keydate (
   keydate_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   keydate_name TEXT NOT NULL,
   user_id INTEGER NOT NULL CONSTRAINT user_id REFERENCES user(id) ON DELETE CASCADE,
   remaining_days INTEGER,
   past_days INTEGER
);
#+END_SRC
