* Design
** Version 0
KeyDays shows the dates that are important to the user. The app displays dates and countdown days to the user.

- User can *scroll through* past dates and upcoming dates.
- Layout is optimized with the ViewHolder pattern.
- For each movie displayed, user can see the following details:
  + Tile, date, past days(or the days left)
- User interface imporved through styling nad coloring and using material design elements such as CardView and Navigation Drawer.
- The app is using Espresso to text the UI interactions.

** Version 1
Date: <2018-10-07 Sun>
MainActivity has left drawerLayout and on the right of the top has ADD button. The user can also change the layout to grid, verse visa.

Log in /Register Activity

*** Activities
1. MainActivity
Cover
List the recorded events -> Right wrap to delete
Menu
Add button -> AddDateActivity

2. LoginActivity

3. AddDateActivity

*** Database
1. table1: users. Record the user name, email and password.
2. table2: keydates. Each user has his own table, which is recorddate.

One-to-many relationship

**** The user table
primary\_key: user\_id

| id       | user\_name  | user\_email | user\_password |
|----------+------------+-------------+----------------|
|          |            |             |                |

#+BEGIN_SRC
CREATE TABLE user (
   id    INTEGER PRIMARY KEY AUTOINCREMENT,
   user_name  TEXT    NOT NULL,
   user_email TEXT    NOT NULL,
   user_password TEXT NOT NULL
);
#+END_SRC

**** The keydate table
primary\_key: keydate_id
foreign key: users(user\_id)

| keydate\_id | keydate\_name | user\_id | remaining\_days | past\_days |
|-------------+---------------+----------+-----------------+------------|
|             |               |          |                 |            |
#+BEGIN_SRC
CREATE TABLE keydate (
   keydate_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   keydate_name TEXT NOT NULL,
   user_id INTEGER NOT NULL CONSTRAINT user_id REFERENCES user(id) ON DELETE CASCADE,
   remaining_days INTEGER,
   past_days INTEGER
);
#+END_SRC

* 开发笔记
1. MVC架构
- Model: models里相关的java文件
- View: 主要是layout里面的文件
- Controller: 用来控制view，主要是activies文件夹下的文件，主要是继承自Activity,Fragment和Service的

2. 在activity\_date\_details.xml里，不需要hard-code每个记录的日期的name,remainingdays和date，这个需要在对应的java里setText。因为这个是根据具体日期来变化的。

3. 一般来说，activity的onCreate()有如下4个作用：
- inflating  widgets and putting them on screen(调用setContentView(int))
- getting references to inflated widgets
- setting listeners on widgets to handle user interaction
- connecting to external model data

要注意，我们每次调用onCreate()时，实际上是override父类的方法

4. 如果不想要actionbar但是activity又继承自AppCompatActivity的话，APP的theme要改成
#+BEGIN_SRC
android:theme="@style/Theme.AppCompat.Light.NoActionBar"
#+END_SRC

5. fragment和activity之间的通信问题：

6. 为了使用自定义的toolbar,需要用noactionbar的主题
#+BEGIN_SRC
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
#+END_SRC
