* Design
** Version 0
KeyDays shows the dates that are important to the user. The app displays dates and countdown days to the user.

- User can *scroll through* past dates and upcoming dates.
- Layout is optimized with the ViewHolder pattern.
- For each movie displayed, user can see the following details:
  + Tile, date, past days(or the days left)
- User interface imporved through styling nad coloring and using material design elements such as CardView and Navigation Drawer.
- The app is using Espresso to text the UI interactions.

** Version 1
Date: <2018-10-07 Sun>
MainActivity has left drawerLayout and on the right of the top has ADD button. The user can also change the layout to grid, verse visa.

Log in /Register Activity

*** Activities
1. MainActivity
Cover
List the recorded events -> Right wrap to delete
Menu
Add button -> AddDateActivity

2. LoginActivity

3. AddDateActivity

*** Database
1. table1: users. Record the user name, email and password.
2. table2: keydates. Each user has his own table, which is recorddate.

One-to-many relationship

**** The user table
primary\_key: user\_id

| id       | user\_name  | user\_email | user\_password |
|----------+------------+-------------+----------------|
|          |            |             |                |

#+BEGIN_SRC
CREATE TABLE user (
   id    INTEGER PRIMARY KEY AUTOINCREMENT,
   user_name  TEXT    NOT NULL,
   user_email TEXT    NOT NULL,
   user_password TEXT NOT NULL
);
#+END_SRC

**** The keydate table
primary\_key: keydate_id
foreign key: users(user\_id)

| keydate\_id | keydate\_name | user\_id | remaining\_days | past\_days |
|-------------+---------------+----------+-----------------+------------|
|             |               |          |                 |            |
#+BEGIN_SRC
CREATE TABLE keydate (
   keydate_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   keydate_name TEXT NOT NULL,
   user_id INTEGER NOT NULL CONSTRAINT user_id REFERENCES user(id) ON DELETE CASCADE,
   remaining_days INTEGER,
   past_days INTEGER
);
#+END_SRC

* 开发笔记
1. MVC架构
- Model: models里相关的java文件
- View: 主要是layout里面的文件
- Controller: 用来控制view，主要是activies文件夹下的文件，主要是继承自Activity,Fragment和Service的

2. 在activity\_date\_details.xml里，不需要hard-code每个记录的日期的name,remainingdays和date，这个需要在对应的java里setText。因为这个是根据具体日期来变化的。

3. 一般来说，activity的onCreate()有如下4个作用：
- inflating  widgets and putting them on screen(调用setContentView(int))
- getting references to inflated widgets
- setting listeners on widgets to handle user interaction
- connecting to external model data

要注意，我们每次调用onCreate()时，实际上是override父类的方法

4. 如果不想要actionbar但是activity又继承自AppCompatActivity的话，APP的theme要改成
#+BEGIN_SRC
android:theme="@style/Theme.AppCompat.Light.NoActionBar"
#+END_SRC

5. fragment和activity之间的通信问题：

6. 为了使用自定义的toolbar,需要用noactionbar的主题
#+BEGIN_SRC
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
#+END_SRC

7. login and register with database

8. selectionArgs
在用sqlite查询的时候，准确地说是，用cursor进行query的时候，函数是
#+BEGIN_SRC
public Cursor query(String table,
                    String[] columns,
                    String selection,
                    String[] selectionArgs,
                    String groupBy,
                    String having,
                    String orderBy);
#+END_SRC

columns就是要返回的列
selection，就是where后面的过滤条件
selectionArgs，是如果selection种有string的时候，用来转义的，在selection中需要嵌入字符串的地方用?代替
举个例子：
#+BEGIN_SRC
public void doQuery(long id, final String name) {
   db.query("TABLE_NAME",
            null,
            "id=" + id + "AND name=?",
            new String[] {name},
            null,
            null,
            null
   );
}
#+END_SRC

9. 关于Date的处理
因为sqlite里面没有getDate()这个method，所以在定义date模型的时候，要把时间设置为Long

10. button的onClickListener()的三种处理办法
- 在activity对应的xml文件中设置onclick对应的事件名
 比如在xml文件中给button设置了add方法
#+BEGIN_SRC
android:onClick="add"
#+END_SRC
 再去对应的java文件中，实现add函数即可
#+BEGIN_SRC
public void add(View view) {

}
#+END_SRC

- 直接在对应的activity中为对应的button设置绑定函数
#+BEGIN_SRC
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  setContentView(R.layout.main);

  findViewById(R.id.Button).setOnClickListener(new OnClickListener(){
    @Override
    public void onClick(View v) {
      Intent intent = new Intent(mainActivity.this, fristActivity.class);
      intent.putExtra("data", "mainActivity");
      startActivity(intent);
    }
  });
}
#+END_SRC

这个的问题是，如果同一个activity中有多个button，代码会看上去很乱

- 最后一种适用于一个页面有多个button
实现setOnClickListener()这个接口
#+BEGIN_SRC
public class mainActivity extends Activity implements OnClickListener{
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);
    findViewById(R.id.Button).setOnClickListener(this);
    findViewById(R.id.Button1).setOnClickListener(this);
  }

  public void onClick(View view) {
    switch (v.getId()) {
      case R.id.Button:
        ...
        break;

      case R.id.Button1:
        ...
        break;
      default:
        break;
    }
  }
}
#+END_SRC

11. 对于每个widget,layout\_width都是必须的！！！即使用了layout\_weight，也需要设置width！！！

12. List events
List views respond to the following events
- setOnItemClickListener(AdapterView.OnItemClickListener)
- setOnItemLongClickListener(AdapterView.OnItemLongClickListener)
- setOnItemSelectedListener(AdapterView.OnItemSelectedListener)
onDrag
onFocusChanged
onHover
onKey
onScroll
onTouch
